### ISSUE TITLE
Cannot find module 'ng2-file-required'.

### ISSUE THREAD

**Issue by ascuet** [pkantsedalov/ng2-file-required#1]
I want to use this for Angular 4 project.
First I ran
 **npm install ng2-file-required --save** 

Then tried the code below in my app.module.ts:
**import { Ng2FileRequiredModule } from 'ng2-file-required';**

But it shows the following error:

**Cannot find module 'ng2-file-required'.**

**Comment by pkantsedalov** [comment]
Hi @ascuet.
Please try latest version (seems to be fixed in [this commit](7b268a9bcada90b1cf6cdb2569f1b441fd3ee18e)).

**Comment by ascuet** [comment]
Hi @pkantsedalov ,
I am using the lastest version of 1.0.1. And I got it from npm. The commit link you provided showing 404.

**Comment by pkantsedalov** [comment]
@ascuet sorry for inconvenience. Try version 1.0.10 instead - this is the latest one for now.

**Comment by ascuet** [comment]
Its working now. Thanks @pkantsedalov
